from stack import Stack
from queue import Queue

s = Stack(3)
s.push(3)
s.push(1)
print("top is located at the leftmost")
print("the capacity I defined is 3")
print(s)
s.push(4)
print("top is located at the leftmost")
print(s)
s.pop()
print("pop one element from the stack")
print(s)
s.push(5)
print("push 5 into the stack")
print(s)
s.push(6)
print("and then push 6 into the stack")
print("the result shown as followed")
print("we can see the new added value has disappeared from the top")
print(s)
print()
print()
print()
hp = Queue(3)
hp.enqueue(1)
hp.enqueue(2)
hp.enqueue(5)
print("back is located at the rightmost")
print("the capacity I defined is 3")
print(hp)
hp.dequeue()
print("dequeue one element from the queue")
print(hp)
hp.enqueue(7)
print("enqueue 7 into the queue")
print(hp)
hp.enqueue(8)
print("then enqueue 8 into the queue")
print("the result shown as followed")
print("we can see the new added value has been placed to the back")
print("the oldest value has been removed from the front")
print(hp)